name: Deploy Dist
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: mylocal
    steps:
      - name: Get code
        uses: actions/checkout@v4
        # run: |
        #   echo "cloning repo.."
        #   echo "${{toJson(github)}}"
        #   git clone https://github.com/${{github.repository}}.git
      - name: install Node 20
        uses: actions/setup-node@v4
        with:
          node-versions: 20
      - name: print node versions
        run: node -v
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test
